// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArVHenUDUHIt4nymAdlYe3saJE9orsl64',
    appId: '1:362051188774:web:432d8a69b46d475e198ee7',
    messagingSenderId: '362051188774',
    projectId: 'work-out-app-6fcba',
    authDomain: 'work-out-app-6fcba.firebaseapp.com',
    storageBucket: 'work-out-app-6fcba.firebasestorage.app',
    measurementId: 'G-GX00NBVRDZ',
    // FIXED URL BELOW:
    databaseURL: 'https://work-out-app-6fcba-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBicBUKL_Zv9cJqI4fFejLK5HqfR8ThAGQ',
    appId: '1:362051188774:android:21dbfd55aeb93199198ee7',
    messagingSenderId: '362051188774',
    projectId: 'work-out-app-6fcba',
    storageBucket: 'work-out-app-6fcba.firebasestorage.app',
    // FIXED URL BELOW:
    databaseURL: 'https://work-out-app-6fcba-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCM-K3pQKIS-QNbUNK8NiNsVI_sLbPVzvI',
    appId: '1:362051188774:ios:814a0ffeb6870f71198ee7',
    messagingSenderId: '362051188774',
    projectId: 'work-out-app-6fcba',
    storageBucket: 'work-out-app-6fcba.firebasestorage.app',
    iosBundleId: 'com.example.workOutApp',
    // FIXED URL BELOW:
    databaseURL: 'https://work-out-app-6fcba-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCM-K3pQKIS-QNbUNK8NiNsVI_sLbPVzvI',
    appId: '1:362051188774:ios:814a0ffeb6870f71198ee7',
    messagingSenderId: '362051188774',
    projectId: 'work-out-app-6fcba',
    storageBucket: 'work-out-app-6fcba.firebasestorage.app',
    iosBundleId: 'com.example.workOutApp',
    // FIXED URL BELOW:
    databaseURL: 'https://work-out-app-6fcba-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArVHenUDUHIt4nymAdlYe3saJE9orsl64',
    appId: '1:362051188774:web:3fcf89306ab6acb4198ee7',
    messagingSenderId: '362051188774',
    projectId: 'work-out-app-6fcba',
    authDomain: 'work-out-app-6fcba.firebaseapp.com',
    storageBucket: 'work-out-app-6fcba.firebasestorage.app',
    measurementId: 'G-4TGN9KVX5P',
    // FIXED URL BELOW:
    databaseURL: 'https://work-out-app-6fcba-default-rtdb.firebaseio.com',
  );
}