import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:work_out_app/screens/wrapper.dart';
// 1. Import the generated Firebase options file
import 'package:work_out_app/firebase_options.dart';

import 'package:get/get.dart';

void main() async {
  // Ensure that Flutter is initialized before calling Firebase.initializeApp()
  WidgetsFlutterBinding.ensureInitialized();
  // 2. Initialize Firebase using the configuration generated by flutterfire configure
  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
    print("Firebase initialized successfully!");
  } catch (e) {
    // Log the error if initialization fails
    print("Error initializing Firebase: $e");
    // You might want to show an error screen here later
  }

  // 3. Run the application
  runApp(const WorkoutApp());
}

// The root widget of your application
class WorkoutApp extends StatelessWidget {
  const WorkoutApp({super.key});

  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Workout Tracker',
      theme: ThemeData(
        // Define your app's theme here
        primarySwatch: Colors.blue,
      ),
      // Set the initial screen of the application
      home: Wrapper(), 
    );
  }
}